"""add monitoring sources and regulatory updates tables

Revision ID: db70148c9922
Revises: fed742ec55b3
Create Date: 2026-05-24 14:54:03.781752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db70148c9922'
down_revision: Union[str, Sequence[str], None] = 'fed742ec55b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_monitoring_sources_id'), 'monitoring_sources', ['id'], unique=False)
    op.create_table('regulatory_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_title', sa.String(length=200), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('chunks_added', sa.Integer(), nullable=True),
    sa.Column('admins_notified', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_updates_id'), 'regulatory_updates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_updates_id'), table_name='regulatory_updates')
    op.drop_table('regulatory_updates')
    op.drop_index(op.f('ix_monitoring_sources_id'), table_name='monitoring_sources')
    op.drop_table('monitoring_sources')
    # ### end Alembic commands ###
