"""add organisations table and org_id to users and assessments

Revision ID: fed742ec55b3
Revises: 
Create Date: 2026-05-23 15:08:44.503616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed742ec55b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('assessment_history', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'org_id')
    op.drop_column('assessment_history', 'org_id')
    op.drop_column('assessment_history', 'user_id')
    # ### end Alembic commands ###
