import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT

DARK_BLUE = HexColor('#1a2f5a')
MEDIUM_BLUE = HexColor('#2563eb')
LIGHT_BLUE = HexColor('#eff6ff')
GREEN = HexColor('#16a34a')
RED = HexColor('#dc2626')
LIGHT_GREY = HexColor('#f8fafc')
DARK_GREY = HexColor('#374151')
MID_GREY = HexColor('#e5e7eb')


def _create_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name='AuditTitle',
        fontSize=22,
        textColor=DARK_BLUE,
        spaceAfter=8,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    ))
    styles.add(ParagraphStyle(
        name='AuditSubtitle',
        fontSize=11,
        textColor=DARK_GREY,
        spaceAfter=4,
        alignment=TA_CENTER,
        fontName='Helvetica'
    ))
    styles.add(ParagraphStyle(
        name='SectionHeader',
        fontSize=13,
        textColor=DARK_BLUE,
        spaceBefore=16,
        spaceAfter=8,
        fontName='Helvetica-Bold'
    ))
    styles.add(ParagraphStyle(
        name='AuditBody',
        fontSize=9,
        textColor=DARK_GREY,
        spaceAfter=4,
        fontName='Helvetica'
    ))
    return styles


def _verify_chain(records: list) -> tuple[bool, list[bool]]:
    if not records:
        return True, []
    per_record_valid = [True]
    chain_valid = True
    for i in range(1, len(records)):
        link_ok = records[i].previous_hash == records[i - 1].record_hash
        per_record_valid.append(link_ok)
        if not link_ok:
            chain_valid = False
    return chain_valid, per_record_valid


def generate_audit_pdf(records: list, org_name: str = "Organisation", output_dir: str = "src/reports") -> str:
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"audit_trail_{timestamp}.pdf"
    filepath = os.path.join(output_dir, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch
    )

    styles = _create_styles()
    story = []
    chain_valid, per_record_valid = _verify_chain(records)

    _add_cover(story, styles, org_name, records, chain_valid)
    _add_summary(story, styles, records, chain_valid)
    _add_records_table(story, styles, records, per_record_valid)
    _add_footer_note(story, styles)

    doc.build(story)
    return filepath


def _add_cover(story, styles, org_name, records, chain_valid):
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph("EU AI Act Governance Platform", styles['AuditSubtitle']))
    story.append(Paragraph("Compliance Audit Trail Report", styles['AuditTitle']))
    story.append(HRFlowable(width="100%", thickness=2, color=MEDIUM_BLUE, spaceAfter=12))

    export_dt = datetime.now().strftime("%d %B %Y at %H:%M UTC")
    story.append(Paragraph(f"Organisation: {org_name}", styles['AuditSubtitle']))
    story.append(Paragraph(f"Exported: {export_dt}", styles['AuditSubtitle']))
    story.append(Paragraph(f"Total records: {len(records)}", styles['AuditSubtitle']))
    story.append(Spacer(1, 0.2 * inch))

    status_text = "CHAIN INTACT - All records verified" if chain_valid else "CHAIN BROKEN - Tampering detected"
    status_color = GREEN if chain_valid else RED

    status_style = ParagraphStyle(
        name='StatusBadge',
        fontSize=12,
        textColor=status_color,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
        spaceBefore=8,
        spaceAfter=8
    )
    story.append(Paragraph(status_text, status_style))
    story.append(HRFlowable(width="100%", thickness=1, color=MID_GREY, spaceAfter=12))


def _add_summary(story, styles, records, chain_valid):
    story.append(Paragraph("Summary", styles['SectionHeader']))

    if not records:
        story.append(Paragraph("No audit records found.", styles['AuditBody']))
        return

    first_dt = records[0].timestamp.strftime("%d %b %Y %H:%M UTC") if records[0].timestamp else "-"
    last_dt = records[-1].timestamp.strftime("%d %b %Y %H:%M UTC") if records[-1].timestamp else "-"

    summary_data = [
        ["Field", "Value"],
        ["Total audit records", str(len(records))],
        ["First record", first_dt],
        ["Most recent record", last_dt],
        ["Chain integrity", "Verified - unbroken" if chain_valid else "FAILED - tampering detected"],
        ["Verification method", "SHA-256 hash chain"],
        ["Generated by", "EU AI Act Governance Platform"],
    ]

    table = Table(summary_data, colWidths=[2.5 * inch, 4.5 * inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), DARK_BLUE),
        ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#ffffff')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [HexColor('#ffffff'), LIGHT_GREY]),
        ('GRID', (0, 0), (-1, -1), 0.5, MID_GREY),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
    ]))
    story.append(table)


def _add_records_table(story, styles, records, per_record_valid):
    story.append(Paragraph("Audit Records", styles['SectionHeader']))
    story.append(Paragraph(
        "Each row is one compliance assessment. Hash shows first 16 characters of the SHA-256 record hash. "
        "Chain column verifies this record links correctly to the previous one.",
        styles['AuditBody']
    ))
    story.append(Spacer(1, 0.1 * inch))

    if not records:
        story.append(Paragraph("No records to display.", styles['AuditBody']))
        return

    header = ["#", "Timestamp", "Action", "System Name", "Hash (first 16)", "Chain"]
    rows = [header]

    for i, record in enumerate(records):
        ts = record.timestamp.strftime("%Y-%m-%d %H:%M") if record.timestamp else "-"
        hash_short = record.record_hash[:16] + "..." if record.record_hash else "-"
        chain_ok = per_record_valid[i] if i < len(per_record_valid) else True
        chain_status = "OK" if chain_ok else "FAIL"

        rows.append([
            str(record.id),
            ts,
            record.action or "-",
            record.system_name or "-",
            hash_short,
            chain_status
        ])

    col_widths = [0.4 * inch, 1.3 * inch, 1.1 * inch, 1.8 * inch, 1.4 * inch, 0.7 * inch]
    table = Table(rows, colWidths=col_widths, repeatRows=1)

    style_commands = [
        ('BACKGROUND', (0, 0), (-1, 0), DARK_BLUE),
        ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#ffffff')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.3, MID_GREY),
        ('PADDING', (0, 0), (-1, -1), 5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [HexColor('#ffffff'), LIGHT_GREY]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]

    for i, valid in enumerate(per_record_valid):
        row_idx = i + 1
        if not valid:
            style_commands.append(('BACKGROUND', (5, row_idx), (5, row_idx), RED))
            style_commands.append(('TEXTCOLOR', (5, row_idx), (5, row_idx), HexColor('#ffffff')))
        else:
            style_commands.append(('TEXTCOLOR', (5, row_idx), (5, row_idx), GREEN))

    table.setStyle(TableStyle(style_commands))
    story.append(table)


def _add_footer_note(story, styles):
    story.append(Spacer(1, 0.3 * inch))
    story.append(HRFlowable(width="100%", thickness=1, color=MID_GREY, spaceAfter=8))
    story.append(Paragraph(
        "This report was generated automatically by the EU AI Act Governance Platform. "
        "The hash chain uses SHA-256 cryptographic hashing. Any modification to a stored record "
        "after creation will cause the chain verification to fail, providing tamper evidence. "
        "This document may be presented to regulatory authorities as evidence of compliance monitoring.",
        styles['AuditBody']
    ))